sudo: true
language: node_js
node_js:
  - "lts/*"
  - "6"
services:
  - docker
before_install:
  - docker pull redis:3
  - docker run -d -p 6379:6379 redis:3
  - sleep 5
script:
  - npm run report
after_script:
  - "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"